### ISSUE TITLE
notifies only for added series, but not for movies

### ISSUE THREAD

**Issue by ChunkyMonkey** [RomainPierre7/jellyfin-plugin-TelegramNotifier#15]
I get only notifications for added series episodes, but not for movies, despite checking all boxes.

**Comment by ChunkyMonkey** [comment]
Hello and thanks for the quick reply. As far as I can tell, the metadata is correctly assigned, a comparison of my metadata and TMDB shows the same text, and the movie category is also displayed correctly.

**Comment by RomainPierre7** [comment]
Maybe try to check your logs. You can for example start a movie, stop it and then go in your logs and search (Ctrl + f) "telegram". You should see some lines at the end relative to the start and the stop playback. It will help us to understand the problem

**Comment by ChunkyMonkey** [comment]
Thanks for your answer! I'm in the process of rebuilding my NAS for other reasons, it will take a few days, I'll get back to you as soon as I've created the logfiles

**Comment by MetalDroid** [comment]
Same here.

Although I have to say that it has been working correctly for me until today.

Here are the logs:

`[2024-12-11 23:16:06.160 +01:00] [ERR] [35] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.TelegramNotifier.Notifiers.ItemAddedNotifier.ItemAddedManager.ProcessItemsAsync()
   at Jellyfin.Plugin.TelegramNotifier.Notifiers.ItemAddedNotifier.ItemAddedManager.ProcessItemsAsync()
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-12-11 23:16:06.171 +01:00] [INF] [35] Emby.Server.Implementations.ScheduledTasks.TaskManager: "TelegramNotifier Item Added Notifier" Failed after 0 minute(s) and 0 seconds`

And here is the playback log:

`[2024-12-11 23:29:37.592 +01:00] [INF] [29] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = "Venom: El último baile"`

Could it be because of the ":" in the item name?

**Comment by RomainPierre7** [comment]
Hi,

Not sure... Do you still have the problem ? Is it only with this movie ?

**Comment by ChunkyMonkey** [comment]
I think I have found the problem: I have Jellyfin running as a Docker container. When I first set it up, I used the IP address of my Jellyfin host (in this case a Synology NAS running Docker) as the server URL (192.168.0.98:8096), which worked, but obviously only from time to time. I have now changed the IP to the Docker gateway used, and now it works perfectly, even with movies etc. The issue can be marked as resolved.

**Comment by RomainPierre7** [comment]
That's good to know, thanks for keeping us informed ;)
