### ISSUE TITLE
It doesn't work with music

### ISSUE THREAD

**Issue by G-Bez** [RomainPierre7/jellyfin-plugin-TelegramNotifier#18]
As per the title, it doesn't work with music, no notifications when adding new music to library, and no notifications when starting or stopping music playback. Except for this issue it works just fine and it's really easy to setup. Thank you for your effort.

**Comment by RomainPierre7** [comment]
Hello, for playbacks this is normal, as it would mean having a notification every 3 minutes on average. However, I may add this option in the future.

For added items, this had been implemented but I hadn't been able to test it properly. I'll make a note of it for the next release.

**Comment by guiu-rocafort** [comment]
I added some albums to a collection, and now i am having this error every time the scheduled task runs:

[2025-02-20 16:27:01.176 +01:00] [ERR] Error executing Scheduled Task
System.ArgumentException: The property ItemAddedAudios does not exist.
   at Jellyfin.Plugin.TelegramNotifier.NotificationFilter.GetPropertyValue(UserConfiguration user, String propertyName)
   at Jellyfin.Plugin.TelegramNotifier.NotificationFilter.Filter(NotificationType type, Object eventArgs, String userId, String imagePath, String subtype)
   at Jellyfin.Plugin.TelegramNotifier.Notifiers.ItemAddedNotifier.ItemAddedManager.ProcessItemsAsync()
   at Jellyfin.Plugin.TelegramNotifier.Notifiers.ItemAddedNotifier.ItemAddedManager.ProcessItemsAsync()
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2025-02-20 16:27:01.177 +01:00] [INF] "TelegramNotifier Item Added Notifier" Failed after 0 minute(s) and 0 seconds

**Comment by RomainPierre7** [comment]
This log means you have to create the relevant property in the user config (look at the config folder)

**Comment by alsoGAMER** [comment]
Hi there, I'm having the same issue here, can you please explain what do you mean by 

> create the relevant property in the user conf ?

What should I do?

**Comment by RomainPierre7** [comment]
That was for another issue but he posted in the wrong. I delete it to not confuse anyone else.

Music is added but not tested. I'll do it in a next release.

**Comment by tomrss** [comment]
Hello @RomainPierre7 , thanks for this plugin. I also have an error with music, I checked the logs and I found this:

```
[12:46:39] [INF] [3] Emby.Server.Implementations.ScheduledTasks.TaskManager: TelegramNotifier Item Added Notifier Failed after 0 minute(s) and 0 seconds
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
   at Jellyfin.Plugin.TelegramNotifier.Notifiers.ItemAddedNotifier.ItemAddedManager.ProcessItemsAsync()
   at Jellyfin.Plugin.TelegramNotifier.Notifiers.ItemAddedNotifier.ItemAddedManager.ProcessItemsAsync()
   at Jellyfin.Plugin.TelegramNotifier.NotificationFilter.Filter(NotificationType type, Object eventArgs, String userId, String imagePath, String subtype)
   at Jellyfin.Plugin.TelegramNotifier.NotificationFilter.GetPropertyValue(UserConfiguration user, String propertyName)
System.ArgumentException: The property ItemAddedAudios does not exist.
```

I had a look on the code: maybe the string at https://github.com/RomainPierre7/jellyfin-plugin-TelegramNotifier/blob/7ef11b10df5817a9c3c81c5520624b0ad28b3d28/Jellyfin.Plugin.TelegramNotifier/Notifiers/ItemAddedNotifier/ItemAddedManager.cs#L98 should match the property in https://github.com/RomainPierre7/jellyfin-plugin-TelegramNotifier/blob/7ef11b10df5817a9c3c81c5520624b0ad28b3d28/Jellyfin.Plugin.TelegramNotifier/Configuration/UserConfiguration.cs#L186

I'm open to submit a PR for that, let me know!

**Comment by RomainPierre7** [comment]
https://github.com/RomainPierre7/jellyfin-plugin-TelegramNotifier/pull/44#issuecomment-2816126028
